DROP TABLE IF EXISTS Authors;
CREATE TABLE IF NOT EXISTS Authors(
    Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    Name TEXT NOT NULL,
    CreatedAt DATETIME);
DROP TABLE IF EXISTS Messages;
CREATE TABLE IF NOT EXISTS Messages(
    Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    AuthorId INTEGER NOT NULL,
    CreatedAt DATETIME,
    Content TEXT NOT NULL);