DROP TABLE IF EXISTS Authors;
CREATE TABLE IF NOT EXISTS 'authors' (
    Id INT NOT NULL AUTO_INCREMENT,
    Name TEXT NOT NULL,
    CreatedAt DATETIME,
    PRIMARY KEY ('Id')
    );
DROP TABLE IF EXISTS Messages;
CREATE TABLE IF NOT EXISTS Messages (
    Id INTEGER NOT NULL AUTO_INCREMENT,
    AuthorId INTEGER NOT NULL,
    CreatedAt DATETIME,
    Content TEXT NOT NULL,
    PRIMARY KEY (`Id`)
    );