# Application configuration
dbType: postgres
dbProfiles:
  sqlite:
    dbFileName: ./sql/messages.db
    createQuery: >
        DROP TABLE IF EXISTS Authors;
        CREATE TABLE IF NOT EXISTS Authors(
          Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
          Name TEXT NOT NULL,
          CreatedAt DATETIME);
        DROP TABLE IF EXISTS Messages;
        CREATE TABLE IF NOT EXISTS Messages(
          Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
          AuthorId INTEGER NOT NULL,
          CreatedAt DATETIME,
          Content TEXT NOT NULL);
  mysql:
    dbSchema: heroku_d869720877b7819
    connectionUrl: b20b350404308e:1cef0188@tcp(eu-cdbr-west-03.cleardb.net)/heroku_d869720877b7819
  postgres:
    dbSchema: dbo
    connectionUrl: user=postgres password=dljaPG1 dbname=test-go-webapp sslmode=disable
